core/Fetch.cpp

Adding a cast to get past the conversion error encountered during build.

Fix build error being caused by a conversion error

---

traces/stf_trace_gen/dromajo_stf_lib.patch

- unmodified patch for dromajo, when applied, did not compile for
me. Added a missing header file.

Fix dromajo patch

---

.github/actions/build/entrypoint.sh
conda/environment.yml

This PR fixes the failures we've been seeing in the Github Action Ubuntu regression script.
Fixes:
- Update CMake to version 3.17 to work around bug in https://gitlab.kitware.com/cmake/cmake/-/issues/20194
- Update to latest stf_lib (includes version check for CMake 3.17)
- Remove `CC` and `CXX` env var overrides from the build script
- The build was attempting to use the Conda build environment with the system compilers, which caused linking errors

Fixes for Github action failures

---

core/Dispatch.hpp

the path of WeightedContextCounter has been changed to sparta/statistics, so fix it in this PR

fix path for WeightedContextCounter

---

core/ExecutePipe.cpp
test/core/rename/CMakeLists.txt
test/core/rename/Rename_test.cpp
test/core/rename/i2f.json
test/core/rename/raw_lsu.json

Changing ExecutePipe.cpp code to set scoreboard based on destination register, not the pipe register. 
Added associated test for checking correct register file's rename registers are used.

i2f Bug Fix

---

arches/isa_json/olympia_uarch_rv64g.json
core/CoreUtils.hpp
core/ExecutePipe.cpp
core/Inst.hpp
core/InstArchInfo.cpp
core/InstArchInfo.hpp
core/MiscUtils.hpp
test/sim/CMakeLists.txt
test/sim/json_tests/fp_transfers.json

Added new pipeline target: `f2i`.  Fixed the JSONs to reflect the intended source/dest direction.

Fixed all of the FP <-> Int transfer types; added a test

---

CMakeLists.txt
core/CPUFactory.cpp
core/CPUFactory.hpp
core/Execute.cpp
core/Execute.hpp
core/Inst.cpp
core/Inst.hpp
core/LSU.cpp
core/LSU.hpp
core/MavisUnit.cpp
core/MemoryAccessInfo.hpp
sim/OlympiaAllocators.hpp
sim/OlympiaSim.cpp
sim/OlympiaSim.hpp
test/core/dispatch/Dispatch_test.cpp
test/core/rename/Rename_test.cpp

Removed some dead code as well.
@h0lyalg0rithm, I added `void onStartingTeardown_() override {}` to the LSU in this PR as an example of what
I was talking about this morning.  This method is called every time just before the unit is destroyed -- either during an 
exception or a clean teardown.

Created the common Allocators class and hooked it up

---

core/Inst.hpp
core/Rename.cpp
core/Rename.hpp
test/core/rename/CMakeLists.txt
test/core/rename/Rename_test.cpp
test/core/rename/amoadd.json

Fixing https://github.com/riscv-software-src/riscv-perf-model/issues/116

Bug fix, tests, and assertion for stall condition

---

traces/README.md
traces/stf_trace_gen/dromajo_stf_lib.patch

improve performance when stf tracing is enabled, issue #55 
retain n_cycles=10000 until the stf trace opc is detected. 
Once the stop opc is detected restore n_cycles=10000
result is better interactivity under linux, improving overall performance and usability when not actively generating a trace.
This is a re-implementation of previous draft PR.
trace opc trigger detection is done in dromajo_template.
trace record creation and handling is done in dromajo_stf.cpp
headers gathered into dromajo_stf.h

jeffnye-gh/dromajo_stf_update

---

core/Inst.hpp
core/LSU.cpp
core/Rename.cpp
test/core/rename/Rename_test.cpp
test/core/rename/expected_output/big_core.out.EXPECTED
test/core/rename/expected_output/big_core_small_rename.out.EXPECTED
test/core/rename/expected_output/medium_core.out.EXPECTED
test/core/rename/expected_output/small_core.out.EXPECTED

Fix renaming to skip renaming of x0 outlined in https://github.com/riscv-software-src/riscv-perf-model/issues/118.
Changes:
- `renameInstructions_()` now checks if a source is x0, if it is and is a data operand for a LSU operation, we still create a data register for it, as we need to check in LSU for x0 before issuing instruction
- Added a boolean `x0` field to `Reg` struct in `RenameData` that tracks if a data register is an `x0` instruction. This helps on reclamation of rename credits in `getAckFromROB_()` to make sure we don't decrement for an x0 data register
- Updated logic to handle for destination reclamation in `getAckFromROB_()` to ensure when we reclaim credits/freelist registers/references, we don't process them for x0 destinations
- Fixed initial allocation of freelist …

Ignore Renaming of x0

---

core/CPUTopology.cpp
core/Decode.cpp
core/ExecutePipe.cpp
core/ExecutePipe.hpp
core/Fetch.cpp
core/Fetch.hpp
core/FlushManager.hpp
core/Inst.cpp
core/Inst.hpp
core/InstGenerator.cpp
core/InstGenerator.hpp
core/LSU.cpp
core/LSU.hpp
core/ROB.cpp
core/ROB.hpp
core/Rename.cpp
core/Rename.hpp
test/sim/CMakeLists.txt

- Fix pipeline flush mechanisms by removing inflight instructions inside functional units, recovering the rename map, and adding trace rewind functionality
- Add FlushCriteria class for requesting flushes to and from the FlushManager
- Update FlushManager to handle and arbitrate between multiple flush sources
- Add flush request port from ExecutePipe to FlushManager intended to be used for mispredicted branches
- Delay completing instructions in ExecutePipe by a cycle to fix execute flush race conditions
- Add branch identification methods for Inst
- Add test to send random flushes from the branch unit

Add execute flushing

---

core/DCache.cpp
core/DCache.hpp
core/MemoryAccessInfo.hpp
mss/BIU.cpp
mss/BIU.hpp
mss/L2Cache.cpp
mss/L2Cache.hpp
mss/MSS.cpp
mss/MSS.hpp
test/core/l2cache/BIUSinkUnit.hpp
test/core/l2cache/L2SourceUnit.hpp
test/core/l2cache/expected_output/hit_case.out.EXPECTED
test/core/l2cache/expected_output/single_access.out.EXPECTED

As part of #143 use MemoryAccessInfo as the standard transaction type for making memory requests outside of the core, instead of instructions.
This paves way for adding an instruction cache, as well as prefetching and more complicated memory subsystems where requests do not always correspond to a particularly instruction.
Changes are minor, mostly just renaming.

Use MemoryAccessInfo instead of Inst for passing requests between caches and MSS

---

README.md
conda/README.md
core/ExecutePipe.cpp
core/ExecutePipe.hpp
core/Inst.hpp
core/LoadStoreInstInfo.hpp
core/MemoryAccessInfo.hpp
core/ROB.cpp
core/ROB.hpp
reports/dhry_report.yaml
test/sim/CMakeLists.txt

This SHA is an example of how to generate PEvents (Performance Events) typically used for correlation 
efforts between a perf model and hardware.
PEvents are a more "compact" form of the pipeout collection pairs, allowing a modeler to specify more direct items 
for collection.  Pipeout pairs can be more elaborate/detailed.  However, with some clever coding, there can be
reuse -- it's not done here.
To generate performance events, use the command line parameter `--pevents <filename> <pevent1,pevent2,...|all>`.
Examples:
```
./olympia traces/dhry_riscv.zstf --pevents retire.out all -i100
./olympia traces/dhry_riscv.zstf --pevents retire.out RETIRE -i100
./olympia traces/dhry_riscv.zstf --pevents retire.out COMPLETE,RETIRE -i100
```
While I was at it, I removed the generated annotation for …

Add an example of PEvent generation

---

core/Dispatch.cpp

Forgot to add an assert to check that there is a dispatcher (thus a subsequent issue queue/execution unit) that can handle a target pipe of an instruction. If one forgets to define one, i.e you forget to define an execution unit to handle `DIV` target pipe, the simulator will end early, but no error will be thrown.

Sparta Assert for Target Pipe without Execution Unit

---

arches/big_core.yaml
arches/medium_core.yaml
arches/small_core.yaml
core/Dispatch.cpp
core/Inst.cpp
core/Inst.hpp
core/ROB.cpp
core/ROB.hpp
traces/example_json.json

This PR is a followup to https://github.com/riscv-software-src/riscv-perf-model/pull/162.
It is also discussed in: https://github.com/riscv-software-src/riscv-perf-model/issues/164
 
This PR changes the way SYS instructions are executed. Previously, SYS instructions did not go through an execution pipe but instead were dispatched to the ROB without delay, and the ROB handled the scoreboard with respect to the destination register. This PR requires the SYS instructions to pass through an execution pipe, thereby obviating any special scoreboard code in the ROB.  With the exception of CSR read instructions, the ROB will flush all SYS instructions.
This feature can be tested by running example_json.json workload, which is part of the make regress suite.  Also, the sys execute pipe was added …

Add SYS execute pipe

---

core/MavisUnit.cpp

I have regression fails, tried on riscv-perf-model and on my fork. 
Please check my work. I did not see any previous reference to this error but I could have missed it.
MavisUnit.cpp was missing this file:
isa_file_path + "/isa_rv64zicsr.json",
these tests failed for me on regress
1 - olympia_json_test (Subprocess aborted)
2 - olympia_json_test_report_text (Subprocess aborted)
3 - olympia_json_test_report_text_direct (Subprocess aborted)
4 - olympia_json_test_report_html (Subprocess aborted)
...
Exception while running
Unknown mnemonic 'csrrw' in ExtractorDirectInfo
...
terminate called after throwing an instance of 'mavis::UnknownMnemonic'
what():  Unknown mnemonic 'csrrw' in ExtractorDirectInfo
...

regress fails on unknown mnemonic csrrw

---

core/Decode.cpp
core/VectorUopGenerator.cpp

The following [code](https://github.com/AaronGChan/riscv-perf-model/blob/5f86ada39301c3181e47236a3c592a5961a48e99/core/Decode.cpp#L274):
```vec_uop_gen_->getNumUopsRemaining() > 1```
doesn't perform correctly for LMUL=2, because the `num_uops_to_generate_` will be decremented to 1 on the `setInst` of `VectorUopGenerator`, so the 2nd uop is never generated.
This PR fixes logic and counting of Uops based on the parent instruction.

Vector Uop Generator Bug

---

arches/isa_json/gen_uarch_rv64v_json.py
arches/isa_json/olympia_uarch_rv64v.json
core/Decode.cpp
core/Inst.cpp
core/Inst.hpp
core/InstArchInfo.cpp
core/InstArchInfo.hpp
core/InstGenerator.cpp
core/IssueQueue.cpp
core/Rename.cpp
core/VectorUopGenerator.cpp
core/VectorUopGenerator.hpp
test/core/vector/CMakeLists.txt
test/core/vector/Vector_test.cpp
test/core/vector/multiple_vset.json
test/core/vector/vmaccvv_e8m4.json

Added support for even more vector arithmetic instructions:
- Vector Single-Width Shift Instructions
- Vector Narrowing Integer Right Shift Instructions
- Vector Single-Width Integer Multiply-Add Instructions
- Vector Widening Integer Multiply-Add Instructions
- Vector Integer Merge Instructions
- Vector Integer Move Instructions
Also redesigned how the vector uop generator handles vector instructions when only 1 uop is needed (e.g, LMUL = 1, certain vector instructions are not sequenced). The vector uop generator will always generate at least one uop which will be used in place of the "parent" instruction. This is necessary because some vector instructions require the source and/or dest registers be added. For example, the multiply-add vector instructions need to have their destination …

Added More Vector Arithmetic Instruction Support

---

.github/workflows/conda/macos_env.yml
conda/environment.yml

build fix for aaron's issue
[#189 ](https://github.com/riscv-software-src/riscv-perf-model/issues/189)
I have added checks to CMakeLists for Flex 2.6.4 and Bison 3.8.2. 
This is a likely cause but I can not duplicate the problem on my system. 
I have specified the versions I have tested with.
I have added guards for the macros in the Flex file (fsl.l), just in case 
I have added werror and wall to fsl cmakefile

fix fsl build - add require and bison/flex versions to cmakelists

---

traces/stf_metadata/README.md
traces/stf_metadata/example/dhrystone.zstf.metadata.yaml

New trace metadata fields:
* trace_id
* workload -> source_code
* stf -> trace_interval -> start_instruction_index, end_instruction_index

source code and trace interval added on stf metadata spec
